### ISSUE TITLE
CMake files refactoring

### ISSUE THREAD

**Issue by anosach-luxoft** [LuxoftSDL/sdl_core_winport#60] opened 2015-12-23 11:42 UTC
- Refactoring of CMakeFiles for all components
- Refactoring Find modules for all 3rd party

**Comment by malirod** [comment] 2015-12-23 12:25
https://cmake.org/Wiki/CMake:How_To_Find_Libraries

**Comment by malirod** [comment] 2016-02-10 10:27
This is the duplicate of the #47

**Closed as completed by malirod** 2016-02-10 10:27 UTC
Labels: WinQT, WinNative
